services:
  - mysql:latest

variables:
  MYSQL_DATABASE: example
  MYSQL_ROOT_PASSWORD: abcd1234

stages:
  - gradle-build


gradle-build:
  stage: gradle-build
  script:
    - ./gradlew clean build

before_script:
  - export GRADLE_USER_HOME=/cache/.gradle
