image: openjdk:8-jdk-alpine

services:
  - mysql:latest

variables:
  SPRING_PROFILES_ACTIVE: "ci"
  MYSQL_DATABASE: example_db
  MYSQL_ROOT_PASSWORD: abcd1234

stages:
  - gradle-build


gradle-build:
  stage: gradle-build
  script:
    - ./gradlew clean build
  artifacts:
    paths:
      - build/
    when: always
    reports:
      junit: build/test-results/test/TEST-*.xml

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle
