version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/example-product-service
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: ./gradlew clean build
      - store_test_results:
          path: build/test-results/test
      - store_artifacts:
          path: build
      - setup_remote_docker:
          docker_layer_caching: true
      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          ./gradlew docker
          docker tag ryandjf/example-product-service:latest ryandjf/example-product-service:$TAG
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push ryandjf/example-product-service:$TAG

  deploy-aws:
    docker:
      - image: circleci/python:2
    working_directory: ~/example-product-service
    steps:
      - checkout
      - run: 
          name: Install aws cli
          command: |
            sudo pip install awscli
            echo "export AWS_REGION=us-east-1" >> $BASH_ENV
            aws --version
      - run: 
          name: Install aws-iam-authenticator
          command: |
            curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/aws-iam-authenticator
            sudo mv ./aws-iam-authenticator /usr/local/bin/aws-iam-authenticator
            sudo chmod +x /usr/local/bin/aws-iam-authenticator
            /usr/local/bin/aws-iam-authenticator --help
      - run: 
          name: Install kubectl
          command: |
            wget -O kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
            sudo chmod +x /usr/local/bin/kubectl
      - run:
          name: Test AWS EKS configuration
          command: |
            aws sts get-caller-identity
            aws eks update-kubeconfig --name istio-on-eks
            sed -i "" "s/BUILD_VERSION/0.1.$CIRCLE_BUILD_NUM/g" deploy/petstore.yaml
            kubectl apply -f deploy/petstore.yaml
            kubectl apply -f deploy/petstore-gateway.yaml
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-aws:
          requires:
            - build
          filters:
            branches:
              only: master