apiVersion: v1
kind: Service
metadata:
  name: example-product-service
  labels:
    app: example-product-service
spec:
  ports:
    - port: 9090
      name: http
  selector:
    app: example-product-app
