apiVersion: v1
kind: Service
metadata:
  name: example-product-service
  labels:
    app: example-product-service
spec:
  type: NodePort
  ports:
    - name: example-product-service
      port: 9090
      nodePort: 30909
  selector:
    app: example-product-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-product-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: example-product-service
        version: v1
    spec:
      containers:
        - image: docker.io/ryandjf/example-product-service:BUILD_VERSION
          imagePullPolicy: IfNotPresent
          name: example-product-service
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
          ports:
            - containerPort: 9090
